// <auto-generated />
using System;
using BrawlStats.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrawlStats.Infrastructure.Migrations
{
    [DbContext(typeof(BrawlStatsDbContext))]
    [Migration("20251115021327_AddManualPLayerStats")]
    partial class AddManualPLayerStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrawlStats.Domain.Entities.Battle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BattleDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BattleTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BrawlerId")
                        .HasColumnType("int");

                    b.Property<string>("BrawlerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrawlerPower")
                        .HasColumnType("int");

                    b.Property<int>("BrawlerTrophies")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsStarPlayer")
                        .HasColumnType("bit");

                    b.Property<string>("Map")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int?>("TrophyChange")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BattleDateTime");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerTag", "BattleTime");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("BrawlStats.Domain.Entities.Brawler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrawlerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BrawlerId")
                        .IsUnique();

                    b.ToTable("Brawlers");
                });

            modelBuilder.Entity("BrawlStats.Domain.Entities.ManualPlayerStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CustomMetricsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OverallStatsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerTag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RecentFormJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlayerTag")
                        .IsUnique();

                    b.ToTable("ManualPlayerStats");
                });

            modelBuilder.Entity("BrawlStats.Domain.Entities.MetaSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrawlerId")
                        .HasColumnType("int");

                    b.Property<string>("BrawlerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Map")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PickRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<int>("TotalGames")
                        .HasColumnType("int");

                    b.Property<int>("TotalWins")
                        .HasColumnType("int");

                    b.Property<string>("TrendDirection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TrendPercentage")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("BrawlerId", "SnapshotDate", "Mode");

                    b.ToTable("MetaSnapshots");
                });

            modelBuilder.Entity("BrawlStats.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClubName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClubTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DuoVictories")
                        .HasColumnType("int");

                    b.Property<int>("ExpLevel")
                        .HasColumnType("int");

                    b.Property<int>("ExpPoints")
                        .HasColumnType("int");

                    b.Property<int>("HighestTrophies")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlayerTag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoloVictories")
                        .HasColumnType("int");

                    b.Property<int>("Trophies")
                        .HasColumnType("int");

                    b.Property<int>("Victories3v3")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerTag")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BrawlStats.Domain.Entities.PlayerAnalytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BestTimeToPlay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ClutchRating")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("ConsistencyScore")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FavoriteBrawler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImprovementTrend")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Last10Losses")
                        .HasColumnType("int");

                    b.Property<decimal>("Last10WinRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("Last10Wins")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastCalculated")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SkillRating")
                        .HasPrecision(10, 4)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.HasIndex("PlayerTag")
                        .IsUnique();

                    b.ToTable("PlayerAnalytics");
                });

            modelBuilder.Entity("BrawlStats.Domain.Entities.PlayerBrawler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrawlerId")
                        .HasColumnType("int");

                    b.Property<string>("BrawlerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HighestTrophies")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("TotalBattles")
                        .HasColumnType("int");

                    b.Property<int>("Trophies")
                        .HasColumnType("int");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrawlerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerTag", "BrawlerId")
                        .IsUnique();

                    b.ToTable("PlayerBrawlers");
                });

            modelBuilder.Entity("BrawlStats.Domain.Entities.PlayerTrophyHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Trophies")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerTag", "RecordedAt");

                    b.ToTable("PlayerTrophyHistory");
                });

            modelBuilder.Entity("BrawlStats.Domain.Entities.Battle", b =>
                {
                    b.HasOne("BrawlStats.Domain.Entities.Player", "Player")
                        .WithMany("Battles")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BrawlStats.Domain.Entities.MetaSnapshot", b =>
                {
                    b.HasOne("BrawlStats.Domain.Entities.Brawler", "Brawler")
                        .WithMany("MetaSnapshots")
                        .HasForeignKey("BrawlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brawler");
                });

            modelBuilder.Entity("BrawlStats.Domain.Entities.PlayerAnalytics", b =>
                {
                    b.HasOne("BrawlStats.Domain.Entities.Player", "Player")
                        .WithOne()
                        .HasForeignKey("BrawlStats.Domain.Entities.PlayerAnalytics", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BrawlStats.Domain.Entities.PlayerBrawler", b =>
                {
                    b.HasOne("BrawlStats.Domain.Entities.Brawler", "Brawler")
                        .WithMany("PlayerBrawlers")
                        .HasForeignKey("BrawlerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrawlStats.Domain.Entities.Player", "Player")
                        .WithMany("PlayerBrawlers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brawler");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BrawlStats.Domain.Entities.PlayerTrophyHistory", b =>
                {
                    b.HasOne("BrawlStats.Domain.Entities.Player", "Player")
                        .WithMany("TrophyHistory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BrawlStats.Domain.Entities.Brawler", b =>
                {
                    b.Navigation("MetaSnapshots");

                    b.Navigation("PlayerBrawlers");
                });

            modelBuilder.Entity("BrawlStats.Domain.Entities.Player", b =>
                {
                    b.Navigation("Battles");

                    b.Navigation("PlayerBrawlers");

                    b.Navigation("TrophyHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
